const mongoose = require('mongoose');

/*
 * This schema stores cached demand forecast results from the ML service.
 * Forecasts are generated by the Python ML pipeline and stored here
 * for fast retrieval by the frontend dashboard.
 */
const forecastItemSchema = new mongoose.Schema({
    date: {
        type: Date,
        required: true,
    },
    dayName: {
        type: String,
    },
    predictedDemand: {
        type: Number,
        required: true,
    },
    confidence: {
        lower: { type: Number },
        upper: { type: Number },
    },
}, { _id: false });

const demandForecastSchema = new mongoose.Schema({
    // Type of forecast: daily, weekly, or monthly
    forecastType: {
        type: String,
        enum: ['daily', 'weekly', 'monthly'],
        required: true,
    },
    // Which ML model produced this forecast
    modelUsed: {
        type: String,
        enum: ['XGBoost', 'SARIMA', 'LSTM'],
        required: true,
    },
    // When the forecast was generated
    generatedAt: {
        type: Date,
        default: Date.now,
        required: true,
    },
    // Forecast horizon description
    forecastHorizon: {
        type: String,
    },
    // Array of forecast data points
    forecastData: [forecastItemSchema],
    // Model accuracy metrics at time of generation
    accuracy: {
        rmse: { type: Number },
        mae: { type: Number },
        mape: { type: Number },
    },
}, {
    timestamps: true,
});

// Index for fast lookup by type and recency
demandForecastSchema.index({ forecastType: 1, generatedAt: -1 });

// Auto-remove forecasts older than 30 days
demandForecastSchema.index({ generatedAt: 1 }, { expireAfterSeconds: 2592000 });

module.exports = mongoose.model('DemandForecast', demandForecastSchema);
